name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new GitHub repository'
        required: true
        type: string

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs (for debug)
        run: |
          echo "Repo name: ${{ github.event.inputs.repo_name }}"

      - name: Create GitHub repo under Dinesh-security-org
        env:
          PORT_TOKEN_WITH_REPO_SCOPE: ${{ secrets.PORT_TOKEN_WITH_REPO_SCOPE }}
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
        run: |
          echo "Using Port Client ID: $PORT_CLIENT_ID"
          echo "Creating repository: $REPO_NAME"

          curl -X POST "https://api.github.com/orgs/Dinesh-security-org/repos" \
            -H "Authorization: token $PORT_TOKEN_WITH_REPO_SCOPE" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"name\":\"$REPO_NAME\"}"
