name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create repo in org
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          curl -X POST https://api.github.com/orgs/DB-Advisory/repos \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{
              \"name\": \"${{ github.event.inputs.repo_name }}\",
              \"private\": false
            }"
