name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create repository in org
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          echo "Creating repository: ${{ github.event.inputs.repo_name }}"
          
          curl -X POST https://api.github.com/orgs/DB-Advisory/repos \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "name": "'"${{ github.event.inputs.repo_name }}"'",
              "description": "'"${{ github.event.inputs.description }}"'",
              "private": ${{ github.event.inputs.private }},
              "auto_init": true
            }'
